
# Generated by CodiumAI

import pytest

class TestHostUpControll:

    # Test with a single host in the file
    def test_single_host(self):
        with open(".hosts.txt", "w") as host_file:
            host_file.write("host1")
        result = host_up_controll()
        assert len(result) == 1
        assert "host1" in result
        assert "1 packets transmitted, 1 received" in result["host1"]
        os.remove(".hosts.txt")

    # Test with multiple hosts in the file
    def test_multiple_hosts(self):
        with open(".hosts.txt", "w") as host_file:
            host_file.write("host1\nhost2\nhost3")
        result = host_up_controll()
        assert len(result) == 3
        assert "host1" in result
        assert "host2" in result
        assert "host3" in result
        assert "1 packets transmitted, 1 received" in result["host1"]
        assert "1 packets transmitted, 1 received" in result["host2"]
        assert "1 packets transmitted, 1 received" in result["host3"]
        os.remove(".hosts.txt")

    # Test with a host that is down
    def test_host_down(self):
        with open(".hosts.txt", "w") as host_file:
            host_file.write("host1")
        result = host_up_controll()
        assert len(result) == 1
        assert "host1" in result
        assert "1 packets transmitted, 0 received" in result["host1"]
        os.remove(".hosts.txt")